# Generated by Django 6.0.4 on 2026-05-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Income', models.FloatField()),
                ('Tenure_Days', models.IntegerField()),
                ('MntWines', models.FloatField()),
                ('MntFruits', models.FloatField()),
                ('MntMeatProducts', models.FloatField()),
                ('MntFishProducts', models.FloatField()),
                ('MntSweetProducts', models.FloatField()),
                ('MntGoldProds', models.FloatField()),
                ('Total_Spent', models.FloatField()),
                ('NumCatalogPurchases', models.IntegerField()),
                ('NumStorePurchases', models.IntegerField()),
                ('NumWebVisitsMonth', models.IntegerField()),
                ('Recency', models.IntegerField()),
                ('Prev_Campaigns', models.IntegerField()),
                ('prediction_result', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
